### ISSUE TITLE
Another note gets wiped out.

### ISSUE THREAD

**Issue by macedotavares** [akaalias/writers-unblock-plugin#1]
If I have a note open in a panel, it gets wiped out instead of the text I've been writing. This happens even if I don't leave the editor after the timer starts.

**Comment by akaalias** [comment]
Thank you so much @macedotavares for reporting this and creating the issue. I'll look into it as soon as I can.

**Comment by akaalias** [comment]
Fixed with this release: https://github.com/akaalias/dangerzone-writing-plugin/releases/tag/0.0.5

Thanks you!
