### ISSUE TITLE
Plugin don't recognize that the text is being written

### ISSUE THREAD

**Issue by plizmol** [akaalias/writers-unblock-plugin#2]
I have Obsidian 0.10.11, and I installed this plugin manually by copying `main.js` and `manifest.json` into plugins directory of my vault. 
When I start the timer the text fades no matter what I do. Even if I type continuously the text gets deleted anyway, so I'm not able to type any more then couple of words. It seems like the plugin doesn't register key presses.

**Comment by akaalias** [comment]
Hi @plizmol! This is a common issue right after installation that you can usually solve with refreshing Obsidian or closing and opening the note before starting the session. See https://forum.obsidian.md/t/dangerzone-flowstate-like-plugin-prototype/8776/51 for details. 

Why are you installing the plugin manually?

**Comment by plizmol** [comment]
I was forced to install plugin manually because there was some CORS issue while I tried to download it from within the app, now the problem is gone, :man_shrugging: 
The refresh worked, thank you very much for quick feedback!
